# Change these first
owner: a116inc # Your GitHub organization or username, where this repository lives
repo: status # The name of this repository

sites:
  - name: A116 Server 101
    url: $URL_A116_NS1
  - name: A116 Server 102
    url: $URL_A116_NS2
  - name: A116 Server 201
    url: $URL_A116_CONTABO1
  - name: A116 Server 301
    url: $URL_A116_CONTABO2
  - name: A116 Server 401
    url: $URL_A116_CAPIM1
  - name: A116 Server 402
    url: $URL_A116_CAPIM2
  - name: A116 Server 501
    url: $URL_A116_CAPIM501
  - name: A116 Server 502
    url: $URL_A116_CAPIM502
  - name: dChat Server
    url: https://dchat.com.br
  - name: A116 Osiris Server
    url: $URL_IFSP

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.a116.com.br
  # baseUrl: /a116/status
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: A116 Server Status
  introTitle: "Acompanhe o status dos serviços da A116 em **tempo real**"
  introMessage: "Atualizações, status de rede, serviços e servidores da A116"
  navbar:
    - title: Status
      href: https://status.a116.com.br
    - title: A116
      href: https://a116.com.br

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
